name: MCUtils
version: 1.3
main: com.itiscaleb.utils.Utils
api-version: 1.18
authors: [ ItisCaleb ]
description: SMP plugin
commands:
  utilrule:
    description: Some useful utility
    usage: /utilrule <something>
    permission: admin
  ptitle:
    description: Title commands
    usage: /ptitle <player> <title>
    permission: admin
  sitem:
    description: Special Item commands
    usage: /sitem <item name>
    permission: admin
